import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


def find_repo_file(start: Path, relative_path: Path):
    cur = start.resolve()
    for _ in range(8):
        candidate = cur / relative_path
        if candidate.exists():
            return candidate
        cur = cur.parent
    raise FileNotFoundError(f"repo file not found: {relative_path}")


def test_generate_present_page_unit(tmp_path):
    # Arrange: create minimal NAVI structure under tmp
    repo = tmp_path
    nav = repo / 'NAVI'
    offices = nav / 'offices' / 'CTO' / 'inbox'
    packages = nav / 'packages' / 'CTO_BATCH-0001_20251225'
    offices.mkdir(parents=True)
    packages.mkdir(parents=True)

    # Create a manifest for the package
    manifest = {
        'batch_id': 1,
        'batch_label': 'BATCH-0001',
        'package': 'CTO_BATCH-0001_20251225',
        'office': 'CTO',
        'created_at': '2025-12-25T00:00:00Z',
        'files': [
            {'filename': 'sample.txt', 'sidecar': 'sample.txt.navi.json', 'metadata': None}
        ]
    }
    (packages / 'manifest.json').write_text(json.dumps(manifest))

    # Put a file in office inbox (simulate delivered package copy)
    (offices / 'CTO_BATCH-0001_20251225').mkdir()
    (offices / 'CTO_BATCH-0001_20251225' / 'sample.txt').write_text('hello')

    # Find generator script in repo by walking parents
    def find_repo_file(start: Path, relative_path: str):
        cur = start.resolve()
        for _ in range(6):
            candidate = cur / relative_path
            if candidate.exists():
                return candidate
            cur = cur.parent
        raise FileNotFoundError(f"repo file not found: {relative_path}")

    src = find_repo_file(Path(__file__), Path('scripts') / 'generate_present_page.py')
    dst_dir = repo / 'scripts'
    dst_dir.mkdir()
    shutil.copy(src, dst_dir / 'generate_present_page.py')

    # Act: run generator in the context of the temp repo
    res = subprocess.run([sys.executable, str(dst_dir / 'generate_present_page.py')], cwd=str(repo), capture_output=True, text=True)

    # Assert
    out_html = repo / 'NAVI' / 'present' / 'index.html'
    assert out_html.exists(), f"present page not generated. stdout: {res.stdout} stderr: {res.stderr}"
    html = out_html.read_text()
    assert 'CTO' in html
    assert 'CTO_BATCH-0001_20251225' in html


def test_mailroom_triggers_present_generation_integration(tmp_path):
    # Arrange: create temp repo layout with runtime and scripts
    repo = tmp_path
    (repo / 'runtime').mkdir()
    (repo / 'scripts').mkdir()

    # Copy mailroom_runner.py and generator into temp repo (find via parent walk)
    src_mail = find_repo_file(Path(__file__), Path('runtime') / 'mailroom_runner.py')
    src_gen = find_repo_file(Path(__file__), Path('scripts') / 'generate_present_page.py')
    shutil.copy(src_mail, repo / 'runtime' / 'mailroom_runner.py')
    shutil.copy(src_gen, repo / 'scripts' / 'generate_present_page.py')

    # Create NAVI/packages and offices so mailroom has something to deliver
    nav = repo / 'NAVI'
    (nav / 'packages' / 'CTO_BATCH-9999_20251225').mkdir(parents=True)
    # package manifest
    manifest = {
        'batch_id': 9999,
        'batch_label': 'BATCH-9999',
        'package': 'CTO_BATCH-9999_20251225',
        'office': 'CTO',
        'created_at': '2025-12-25T00:00:00Z',
        'files': [
            {'filename': 'sample_in_pkg.txt', 'sidecar': 'sample_in_pkg.txt.navi.json', 'metadata': None}
        ]
    }
    (nav / 'packages' / 'CTO_BATCH-9999_20251225' / 'manifest.json').write_text(json.dumps(manifest))

    # Create package contents so mailroom copytree will find files
    pdir = nav / 'packages' / 'CTO_BATCH-9999_20251225'
    (pdir / 'sample_in_pkg.txt').write_text('pkg')

    # Ensure an office inbox exists
    (nav / 'offices' / 'CTO' / 'inbox').mkdir(parents=True)

    # Act: run the mailroom runner from temp runtime
    res = subprocess.run([sys.executable, str(repo / 'runtime' / 'mailroom_runner.py')], cwd=str(repo), capture_output=True, text=True)

    # Assert: present page generated
    out_html = repo / 'NAVI' / 'present' / 'index.html'
    assert out_html.exists(), f"present page not generated by mailroom. stdout: {res.stdout} stderr: {res.stderr}"
    html = out_html.read_text()
    assert 'CTO_BATCH-9999_20251225' in html
    assert 'sample_in_pkg.txt' in html
